### ISSUE TITLE
Menu fleshed out

### ISSUE THREAD

**Issue by VagishVela** [ificiana/pyweek35#20]
- [x] Get all the buttons working
- [x] Get the text on the story intro

## Updates
Only the CONTINUE button is left, rest are implemented
- [x] rename CONTINUE to SELECT LEVEL
- [x] fill the credits screen

**Comment by ificiana** [comment]
Only the CONTINUE button is left, rest are implemented
- [ ] rename CONTINUE to SELECT LEVEL
- [ ] fill the credits screen
