### ISSUE TITLE
Landing page and Menu

### ISSUE THREAD

**Issue by ificiana** [ificiana/pyweek35#9]

**Comment by VagishVela** [comment]
@ificiana @gods-gift I've merged in the PR #14.

A couple notes:
 - Merge the `myver` into `__main__.py` so the menu shows up when you start the game. 
 - Fix some of the bugs on the different clicks

A question, do we need to move the inventory and game into views as well?

**Comment by ificiana** [comment]
I guess it'd make more sense in views
